export const GLOSSARY: Record<string, string> = {
  // Hitting
  avg: "Batting Average — hits divided by at-bats.",
  obp: "On-Base Percentage — times reaching base divided by plate appearances.",
  slg: "Slugging — total bases divided by at-bats.",
  ops: "On-Base Plus Slugging — OBP + SLG.",
  iso: "Isolated Power — SLG minus AVG (extra-base power).",
  babip: "Batting Average on Balls in Play.",
  wrcPlus: "Weighted Runs Created Plus — runs created vs league avg (100).",
  hr: "Home Runs.",
  rbi: "Runs Batted In.",
  sb: "Stolen Bases.",
  r: "Runs Scored.",
  h: "Hits.",
  // Pitching
  era: "Earned Run Average — earned runs allowed per 9 innings.",
  whip: "Walks + Hits per Inning Pitched.",
  fip: "Fielding Independent Pitching — ERA-scale of K, BB, HR.",
  eraPlus: "ERA+ — ERA vs league avg (100, higher is better).",
  k: "Strikeouts.",
  k9: "Strikeouts per 9 innings pitched.",
  bb: "Walks (Bases on Balls).",
  bb9: "Walks per 9 innings pitched.",
  ip: "Innings Pitched.",
  er: "Earned Runs allowed.",
  w: "Wins.",
  l: "Losses.",
  sv: "Saves.",
  hld: "Holds.",
  so: "Strikeouts (pitching/hitting).",
  // Standings
  pct: "Win percentage — wins / (wins + losses).",
  gb: "Games Behind division leader.",
  wcgb: "Wild Card Games Behind.",
  "m#": "Magic Number — combined wins by leader + losses by trailer to clinch.",
  rs: "Runs Scored (season totals).",
  ra: "Runs Allowed (season totals).",
  diff: "Run differential — RS minus RA.",
  pythw: "Pythagorean wins — projected wins from runs scored/allowed.",
  l10: "Record over the last 10 games.",
  strk: "Current streak — W or L plus length.",
  // Statcast & advanced
  war: "Wins Above Replacement — total value vs a replacement-level player, in wins.",
  woba: "Weighted On-Base Average — one rate weighting each way of reaching base by run value.",
  wraa: "Weighted Runs Above Average — batting runs above league average.",
  xba: "Expected Batting Average — AVG expected from each ball's exit velocity + launch angle.",
  xslg: "Expected Slugging — SLG expected from contact quality.",
  xwoba: "Expected wOBA — wOBA expected from contact quality (plus strikeouts and walks).",
  xwobacon: "Expected wOBA on Contact — xwOBA on batted balls only.",
  barrel: "Barrel% — share of batted balls with the ideal exit-velo + launch-angle combo.",
  ev: "Exit Velocity — how hard the ball leaves the bat, in mph.",
  maxev: "Max Exit Velocity — the batter's hardest-hit ball of the season.",
  hardhit: "Hard-Hit% — share of batted balls hit 95+ mph.",
  la: "Launch Angle — vertical angle of the ball off the bat, in degrees.",
  sprint: "Sprint Speed — feet per second in a player's fastest one-second window.",
  batspeed: "Bat Speed — average speed of the bat head through the zone, in mph.",
  whiff: "Whiff% — swings and misses as a share of total swings.",
  chase: "Chase% — swings at pitches outside the strike zone.",
  oaa: "Outs Above Average — Statcast range-based fielding runs saved.",
  xfip: "Expected FIP — FIP with home runs normalized to a league fly-ball rate.",
  pctl: "Percentile — a player's Statcast rank vs the league, 0 (worst) to 100 (best).",
  zones: "Hot/Cold Zones — a batter's results by pitch location in the strike zone.",
};

export function glossary(name: string): string | undefined {
  return GLOSSARY[name.toLowerCase()];
}
