import { Heart } from "lucide-react";
import { Card, SectionTitle } from "../components/ui/Primitives";

const GITHUB_URL = "https://github.com/xavidop";

// lucide-react dropped its brand icons, so use the GitHub mark inline.
function GithubMark({ size = 14 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden="true"
    >
      <path d="M12 .5C5.37.5 0 5.78 0 12.29c0 5.21 3.44 9.62 8.21 11.18.6.11.82-.25.82-.56 0-.28-.01-1.02-.02-2-3.34.71-4.04-1.59-4.04-1.59-.55-1.36-1.33-1.73-1.33-1.73-1.09-.73.08-.72.08-.72 1.2.08 1.84 1.21 1.84 1.21 1.07 1.8 2.81 1.28 3.5.98.11-.76.42-1.28.76-1.58-2.67-.3-5.47-1.31-5.47-5.81 0-1.28.47-2.33 1.23-3.15-.12-.3-.53-1.51.12-3.15 0 0 1.01-.32 3.3 1.2a11.6 11.6 0 0 1 3-.4c1.02 0 2.05.13 3 .4 2.29-1.52 3.3-1.2 3.3-1.2.65 1.64.24 2.85.12 3.15.77.82 1.23 1.87 1.23 3.15 0 4.51-2.81 5.5-5.49 5.79.43.36.81 1.08.81 2.18 0 1.58-.01 2.85-.01 3.24 0 .31.22.68.83.56A12.02 12.02 0 0 0 24 12.29C24 5.78 18.63.5 12 .5z" />
    </svg>
  );
}

function Ext({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="text-volt-500 hover:text-volt-400 underline underline-offset-2"
    >
      {children}
    </a>
  );
}

export default function AboutPage() {
  return (
    <div>
      <SectionTitle title="About" subtitle="What Diamond is — and isn't" />

      {/* Dedication */}
      <Card className="mb-4 sm:mb-5">
        <p className="text-base sm:text-lg leading-relaxed text-white">
          <span className="font-display font-black uppercase tracking-tight">
            Diamond
          </span>{" "}
          is a fast, beautiful way to explore Major League Baseball stats — live
          scores, standings, players, leaders, and an AI assistant,
          DiamondGPT — all built on the public MLB Stats API.
        </p>
        <p className="mt-4 flex flex-wrap items-center gap-x-2 gap-y-1 text-sm text-pitch-300">
          <Heart size={14} className="shrink-0 text-volt-500" />
          <span>
            Built by <Ext href={GITHUB_URL}>xavidop</Ext> for all baseball
            lovers.
          </span>
        </p>
        <a
          href={GITHUB_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="btn mt-4 inline-flex w-full justify-center sm:w-auto sm:justify-start"
        >
          <GithubMark size={14} />
          View on GitHub
        </a>
      </Card>

      {/* Legal */}
      <Card>
        <h2 className="page-eyebrow mb-3">Disclaimer</h2>
        <div className="grid gap-4 sm:grid-cols-2 sm:gap-x-10 text-sm leading-relaxed text-pitch-300">
          <p>
            Diamond is an independent, non-commercial project made for
            educational and informational purposes.
          </p>
          <p>
            <span className="font-semibold text-white">
              Not affiliated with MLB.
            </span>{" "}
            Diamond is not affiliated with, endorsed by, sponsored by, or
            approved by Major League Baseball (MLB), MLB Advanced Media, the
            Office of the Commissioner of Baseball, or any MLB club. “MLB,” team
            names, logos, and all related marks are trademarks of their
            respective owners and are used here for identification purposes only.
          </p>
          <p>
            <span className="font-semibold text-white">Data.</span> Statistics
            and game data come from the public MLB Stats API (
            <Ext href="https://statsapi.mlb.com">statsapi.mlb.com</Ext>) and
            remain the property of their respective owners. Diamond makes no
            guarantee as to the accuracy, completeness, or timeliness of any
            information shown.
          </p>
          <p>
            <span className="font-semibold text-white">AI.</span> DiamondGPT
            answers are generated by third-party language models and may be
            inaccurate or incomplete. Nothing here is betting, financial, or
            other professional advice.
          </p>
        </div>
      </Card>
    </div>
  );
}
